### PR TITLE
Update to onnxruntime 1.6.0

### PR DESCRIPTION
**Pull request by marshallpierce**
Re-ran `cargo build --package onnxruntime-sys --features generate-bindings` as per comment in build.rs.

### CODE REVIEW

**Comment by nbigaouette** [comment]
I _think_ the bindings need to be generated on Windows and Linux separately. Are you able to do so? If not I'll see if I can get back to this...

**Comment by marshallpierce** [comment]
I don't have access to a windows box. If you don't beat me to it, I'll see if I can get it working on Microsoft's free IE testing VMs.

**Comment by nbigaouette** [comment]
For Linux Docker is fine. For Windows I used this: https://github.com/nbigaouette/windows_vagrant_rust

I can push a commit if you want.

**Comment by marshallpierce** [comment]
Please do; I'm on mediocre hotel internet so VMs take forever to download.

**Comment by nbigaouette** [comment]
I raise you my crappy laptop that chokes on VMs 😂 

Got the Linux bindings generated. Doing the windows ones now.

I'm not sure how to handle the git repo though. Since you forked my repo, I can't push to your branch. So while I have the commit I can't include it in this PR... or can I?

**Comment by marshallpierce** [comment]
I granted you write access to my fork; it should let you push now

**Comment by nbigaouette** [comment]
Thanks! Windows bindings are building...

**Review by nbigaouette — APPROVED** [review]
Thanks!!

**Pull request merged**
